#!/usr/bin/env python3

import json, re, subprocess
from os.path import isfile
from urllib.request import urlopen

lockfile = "sources.lock.json"

pat = re.compile(r"(.*?)\s*:\s*(.*?)\s*/\s*(.*?)(\s*@\s*(.*))?")
oldlock = json.load(open(lockfile)) if isfile(lockfile) else {}
lock = {}

for line in open("sources.txt").readlines():
    line = line.strip()
    if not line: continue

    m = pat.fullmatch(line)
    name = m[1]
    owner = m[2]
    repo = m[3]
    ref = m[5] or "master"

    rev = json.load(urlopen(f"https://api.github.com/repos/{owner}/{repo}/git/trees/{ref}"))["sha"]

    def getsha256():
        if name in oldlock:
            src = oldlock[name]
            if src["owner"] == owner and src["repo"] == repo and src["rev"] == rev:
                return src["sha256"]
        return subprocess.run(
            [
                "nix-prefetch-url",
                "--unpack",
                f"https://github.com/{owner}/{repo}/archive/{rev}.tar.gz",
            ],
            check = True,
            stdout = subprocess.PIPE,
            text = True,
        ).stdout.strip()

    lock[name] = {
        "owner": owner,
        "repo": repo,
        "rev": rev,
        "sha256": getsha256(),
    }

json.dump(lock, open(lockfile, "w"))
