name: ci

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25

      - name: Set up cachix
        uses: cachix/cachix-action@v15
        with:
          name: figsoda
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build with nix
        run: nix build .#{rust-templates,ymdl}
